### ISSUE TITLE
Rotating image by 90 degrees crashes OS

### ISSUE THREAD

**Issue by wonkoderverstaendige** [fpbattaglia/obj_scorer#1]
Image size changes with rotation.

**Comment by fpbattaglia** [comment]
this wasn't happening on other systems. 
Rotation is operated by a combination of opencv functions (flip and transpose), which shouldn't change the image size. 
Which camera are you using?

**Comment by wonkoderverstaendige** [comment]
Object Scorer, not Operating system...

This happened because we rotated the camera after it started writing video, then video writer gets the wrong image shape. Doesn't happen if you rotate before starting anything else.

**Comment by fpbattaglia** [comment]
still, we haven't had an issue either with Windows or Linux. I'm wondering, if you use the point gray, perhaps there's an issue with the way the image is buffered, and I may have to add an extra memory copy

**Comment by fpbattaglia** [comment]
This is fixed in the new version, resize/rotate video is disabled when you start recording
