### ISSUE TITLE
Seperate file types with file endings

### ISSUE THREAD

**Issue by wonkoderverstaendige** [fpbattaglia/obj_scorer#11]
Instruction sheet, result files and log files should have separate file endings to see quickly what data is available.

E.g. .score, .score_log, .score_result

**Comment by fpbattaglia** [comment]
do you mean extensions? I'd rather keep csv so that programs like Excel won't have a problem recognizing them, but we can do _log.csv (which I think is already the case) _results.csv, etc

**Comment by fpbattaglia** [comment]
as of 24796ae6eedafac7160cec69257f14188bb88162 
the sheet file has a suffix "_sheet.csv" so that they can be easily identified
