### ISSUE TITLE
Automatically open webcam on startup

### ISSUE THREAD

**Issue by wonkoderverstaendige** [fpbattaglia/obj_scorer#20]
No need to select the camera. Attempt first camera, offer dialog from menu to change cameras on request by user.

**Comment by fpbattaglia** [comment]
I'm doing something a little different, but hopefully equivalent. Camera_id can now be specified in the config file, and camera id dialog will only be presented if nothing is specified in the config file. Adding some related improvements (see also #25) will close when those are done

**Comment by fpbattaglia** [comment]
as of ecb0f8a5fae16abc2460fba894cf81aefe046915 
the camera id can be set in the config file
