### ISSUE TITLE
Logfiles: frames

### ISSUE THREAD

**Issue by Iglohut** [fpbattaglia/obj_scorer#23]
Frames in the logfiles are now cumulative. This makes it impossible to relate frames to specific videos. This is because of the black nonrecorded part in the beginning and end of a video that remains unlogged.

Suggestion: everytime a new trial(run/video whatever) is started, reset frames in logfiles to 0, such that the count of frames maps directly to the videos.

**Comment by fpbattaglia** [comment]
so you want all frames in each video counted, that is the first black frame is frame 0?

**Comment by fpbattaglia** [comment]
in the new version, this is already the case, the frame number is updated each time a new video is started. See for example:
[mouse_habituation_OS_log 2.csv.txt](https://github.com/MemDynLab/score/files/2533963/mouse_habituation_OS_log.2.csv.txt)

Please test this, I'm closing the issue, please re-open if there are still problems
