### ISSUE TITLE
Enhance embedded timestamps

### ISSUE THREAD

**Issue by wonkoderverstaendige** [fpbattaglia/obj_scorer#6]
- make machine readable by separation from video image, e.g. white text on black background. For example by adding a black bar at the bottom to not touch the original image

- Additional information [ ISO-DATE, LOCAL TIME, TRIAL RUNTIME, FRAME# ]

**Comment by fpbattaglia** [comment]
as of c0ce57379da0b85d5a78205766fbb05f4ccc3d02 all information, including trial on/off and timestamps are in two status bars above and below the video, in this way the original video stays untouched alleviating the need for saving raw video. Raw video saving can be turned on/off from config file
