### ISSUE TITLE
Move highlight rectangles

### ISSUE THREAD

**Issue by wonkoderverstaendige** [fpbattaglia/obj_scorer#7]
Move the interaction highlight rectangles away from the corners a bit

**Comment by fpbattaglia** [comment]
Is this because of the timestamps? if so, it will be superseded by #6 please advice

**Comment by fpbattaglia** [comment]
trial rectangles are now in the status bars, not to touch the original video

**Comment by fpbattaglia** [comment]
as of c0ce57379da0b85d5a78205766fbb05f4ccc3d02
