### ISSUE TITLE
Store per-video log file

### ISSUE THREAD

**Issue by wonkoderverstaendige** [fpbattaglia/obj_scorer#9]
Instead of/additionally to the central log file, store a per-video log file with per-frame information (TS, image source).

**Comment by fpbattaglia** [comment]
as of 2ff93355ffe7752a54fb78834d388705a945d2ce a per trial log file, with the same prefix file name as the video file, can be obtained by settign in the config file "log_file_per_trial" in the "data_manager" section to true
